/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables.records;


import fr.versefactory.template.storage.tables.BoxPet;

import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BoxPetRecord extends UpdatableRecordImpl<BoxPetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>versefactory.box_pet.id</code>.
     */
    public BoxPetRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.box_pet.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>versefactory.box_pet.box_id</code>.
     */
    public BoxPetRecord setBoxId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.box_pet.box_id</code>.
     */
    @NotNull
    public UUID getBoxId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>versefactory.box_pet.pet_id</code>.
     */
    public BoxPetRecord setPetId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.box_pet.pet_id</code>.
     */
    @NotNull
    public UUID getPetId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>versefactory.box_pet.drop_chance</code>.
     */
    public BoxPetRecord setDropChance(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.box_pet.drop_chance</code>.
     */
    @NotNull
    public BigDecimal getDropChance() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BoxPetRecord
     */
    public BoxPetRecord() {
        super(BoxPet.BOX_PET);
    }

    /**
     * Create a detached, initialised BoxPetRecord
     */
    public BoxPetRecord(UUID id, UUID boxId, UUID petId, BigDecimal dropChance) {
        super(BoxPet.BOX_PET);

        setId(id);
        setBoxId(boxId);
        setPetId(petId);
        setDropChance(dropChance);
        resetChangedOnNotNull();
    }
}
