/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables.records;


import fr.versefactory.template.storage.tables.Box;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BoxRecord extends UpdatableRecordImpl<BoxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>versefactory.box.id</code>.
     */
    public BoxRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.box.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>versefactory.box.name</code>.
     */
    public BoxRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.box.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>versefactory.box.description</code>.
     */
    public BoxRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.box.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>versefactory.box.price</code>.
     */
    public BoxRecord setPrice(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.box.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>versefactory.box.created_at</code>.
     */
    public BoxRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.box.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BoxRecord
     */
    public BoxRecord() {
        super(Box.BOX);
    }

    /**
     * Create a detached, initialised BoxRecord
     */
    public BoxRecord(UUID id, String name, String description, BigDecimal price, LocalDateTime createdAt) {
        super(Box.BOX);

        setId(id);
        setName(name);
        setDescription(description);
        setPrice(price);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
