/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables.records;


import fr.versefactory.template.storage.tables.Example;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExampleRecord extends UpdatableRecordImpl<ExampleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>versefactory.example.id</code>.
     */
    public ExampleRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.example.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>versefactory.example.name</code>.
     */
    public ExampleRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.example.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExampleRecord
     */
    public ExampleRecord() {
        super(Example.EXAMPLE);
    }

    /**
     * Create a detached, initialised ExampleRecord
     */
    public ExampleRecord(Long id, String name) {
        super(Example.EXAMPLE);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
