/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables.records;


import fr.versefactory.template.storage.tables.FactoryPet;

import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactoryPetRecord extends UpdatableRecordImpl<FactoryPetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>versefactory.factory_pet.id</code>.
     */
    public FactoryPetRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory_pet.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>versefactory.factory_pet.factory_id</code>.
     */
    public FactoryPetRecord setFactoryId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory_pet.factory_id</code>.
     */
    @NotNull
    public UUID getFactoryId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>versefactory.factory_pet.pet_id</code>.
     */
    public FactoryPetRecord setPetId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory_pet.pet_id</code>.
     */
    @NotNull
    public UUID getPetId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>versefactory.factory_pet.acquired_at</code>.
     */
    public FactoryPetRecord setAcquiredAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory_pet.acquired_at</code>.
     */
    public LocalDateTime getAcquiredAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FactoryPetRecord
     */
    public FactoryPetRecord() {
        super(FactoryPet.FACTORY_PET);
    }

    /**
     * Create a detached, initialised FactoryPetRecord
     */
    public FactoryPetRecord(UUID id, UUID factoryId, UUID petId, LocalDateTime acquiredAt) {
        super(FactoryPet.FACTORY_PET);

        setId(id);
        setFactoryId(factoryId);
        setPetId(petId);
        setAcquiredAt(acquiredAt);
        resetChangedOnNotNull();
    }
}
