/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables.records;


import fr.versefactory.template.storage.tables.FactoryUpgrade;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactoryUpgradeRecord extends UpdatableRecordImpl<FactoryUpgradeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>versefactory.factory_upgrade.factory_id</code>.
     */
    public FactoryUpgradeRecord setFactoryId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory_upgrade.factory_id</code>.
     */
    @NotNull
    public UUID getFactoryId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>versefactory.factory_upgrade.upgrade_id</code>.
     */
    public FactoryUpgradeRecord setUpgradeId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory_upgrade.upgrade_id</code>.
     */
    @NotNull
    @Size(max = 25)
    public String getUpgradeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>versefactory.factory_upgrade.level</code>.
     */
    public FactoryUpgradeRecord setLevel(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory_upgrade.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>versefactory.factory_upgrade.created_at</code>.
     */
    public FactoryUpgradeRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory_upgrade.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>versefactory.factory_upgrade.updated_at</code>.
     */
    public FactoryUpgradeRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory_upgrade.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FactoryUpgradeRecord
     */
    public FactoryUpgradeRecord() {
        super(FactoryUpgrade.FACTORY_UPGRADE);
    }

    /**
     * Create a detached, initialised FactoryUpgradeRecord
     */
    public FactoryUpgradeRecord(UUID factoryId, String upgradeId, Integer level, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(FactoryUpgrade.FACTORY_UPGRADE);

        setFactoryId(factoryId);
        setUpgradeId(upgradeId);
        setLevel(level);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
