/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables.records;


import fr.versefactory.template.storage.tables.Factory;

import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactoryRecord extends UpdatableRecordImpl<FactoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>versefactory.factory.id</code>.
     */
    public FactoryRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>versefactory.factory.user_id</code>.
     */
    public FactoryRecord setUserId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory.user_id</code>.
     */
    @NotNull
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>versefactory.factory.balance</code>.
     */
    public FactoryRecord setBalance(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory.balance</code>.
     */
    public BigDecimal getBalance() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>versefactory.factory.last_updated_at</code>.
     */
    public FactoryRecord setLastUpdatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.factory.last_updated_at</code>.
     */
    public LocalDateTime getLastUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FactoryRecord
     */
    public FactoryRecord() {
        super(Factory.FACTORY);
    }

    /**
     * Create a detached, initialised FactoryRecord
     */
    public FactoryRecord(UUID id, UUID userId, BigDecimal balance, LocalDateTime lastUpdatedAt) {
        super(Factory.FACTORY);

        setId(id);
        setUserId(userId);
        setBalance(balance);
        setLastUpdatedAt(lastUpdatedAt);
        resetChangedOnNotNull();
    }
}
