/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables.records;

import fr.versefactory.template.storage.tables.Pet;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PetRecord extends UpdatableRecordImpl<PetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>versefactory.pet.id</code>.
     */
    public PetRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.pet.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>versefactory.pet.name</code>.
     */
    public PetRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.pet.name</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>versefactory.pet.rarity</code>.
     */
    public PetRecord setRarity(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.pet.rarity</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getRarity() {
        return (String) get(2);
    }

    /**
     * Setter for <code>versefactory.pet.income_per_second</code>.
     */
    public PetRecord setIncomePerSecond(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.pet.income_per_second</code>.
     */
    public BigDecimal getIncomePerSecond() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>versefactory.pet.base_cost</code>.
     */
    public PetRecord setBaseCost(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.pet.base_cost</code>.
     */
    public BigDecimal getBaseCost() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PetRecord
     */
    public PetRecord() {
        super(Pet.PET);
    }

    /**
     * Create a detached, initialised PetRecord
     */
    public PetRecord(UUID id, String name, String rarity, BigDecimal incomePerSecond, BigDecimal baseCost) {
        super(Pet.PET);

        setId(id);
        setName(name);
        setRarity(rarity);
        setIncomePerSecond(incomePerSecond);
        setBaseCost(baseCost);
        resetChangedOnNotNull();
    }
}
