/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables.records;


import fr.versefactory.template.storage.tables.Upgrade;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UpgradeRecord extends UpdatableRecordImpl<UpgradeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>versefactory.upgrade.id</code>.
     */
    public UpgradeRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.upgrade.id</code>.
     */
    @NotNull
    @Size(max = 25)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>versefactory.upgrade.name</code>.
     */
    public UpgradeRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.upgrade.name</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>versefactory.upgrade.description</code>.
     */
    public UpgradeRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.upgrade.description</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>versefactory.upgrade.type</code>.
     */
    public UpgradeRecord setType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.upgrade.type</code>.
     */
    @NotNull
    @Size(max = 50)
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>versefactory.upgrade.max_level</code>.
     */
    public UpgradeRecord setMaxLevel(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>versefactory.upgrade.max_level</code>.
     */
    public Integer getMaxLevel() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UpgradeRecord
     */
    public UpgradeRecord() {
        super(Upgrade.UPGRADE);
    }

    /**
     * Create a detached, initialised UpgradeRecord
     */
    public UpgradeRecord(String id, String name, String description, String type, Integer maxLevel) {
        super(Upgrade.UPGRADE);

        setId(id);
        setName(name);
        setDescription(description);
        setType(type);
        setMaxLevel(maxLevel);
        resetChangedOnNotNull();
    }
}
