/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage;


import fr.versefactory.template.storage.tables.Factory;
import fr.versefactory.template.storage.tables.FactoryPet;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in versefactory.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_FACTORY_PET_FACTORY_ID = Internal.createIndex(DSL.name("idx_factory_pet_factory_id"), FactoryPet.FACTORY_PET, new OrderField[] { FactoryPet.FACTORY_PET.FACTORY_ID }, false);
    public static final Index IDX_FACTORY_PET_PET_ID = Internal.createIndex(DSL.name("idx_factory_pet_pet_id"), FactoryPet.FACTORY_PET, new OrderField[] { FactoryPet.FACTORY_PET.PET_ID }, false);
    public static final Index IDX_FACTORY_USER_ID = Internal.createIndex(DSL.name("idx_factory_user_id"), Factory.FACTORY, new OrderField[] { Factory.FACTORY.USER_ID }, false);
}
