/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage;


import fr.versefactory.template.storage.tables.AppUser;
import fr.versefactory.template.storage.tables.Example;
import fr.versefactory.template.storage.tables.Factory;
import fr.versefactory.template.storage.tables.FactoryPet;
import fr.versefactory.template.storage.tables.Pet;
import fr.versefactory.template.storage.tables.records.AppUserRecord;
import fr.versefactory.template.storage.tables.records.ExampleRecord;
import fr.versefactory.template.storage.tables.records.FactoryPetRecord;
import fr.versefactory.template.storage.tables.records.FactoryRecord;
import fr.versefactory.template.storage.tables.records.PetRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * versefactory.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppUserRecord> APP_USER_PKEY = Internal.createUniqueKey(AppUser.APP_USER, DSL.name("app_user_pkey"), new TableField[] { AppUser.APP_USER.ID }, true);
    public static final UniqueKey<ExampleRecord> EXAMPLE_PKEY = Internal.createUniqueKey(Example.EXAMPLE, DSL.name("example_pkey"), new TableField[] { Example.EXAMPLE.ID }, true);
    public static final UniqueKey<FactoryRecord> FACTORY_PKEY = Internal.createUniqueKey(Factory.FACTORY, DSL.name("factory_pkey"), new TableField[] { Factory.FACTORY.ID }, true);
    public static final UniqueKey<FactoryRecord> FACTORY_USER_ID_KEY = Internal.createUniqueKey(Factory.FACTORY, DSL.name("factory_user_id_key"), new TableField[] { Factory.FACTORY.USER_ID }, true);
    public static final UniqueKey<FactoryPetRecord> FACTORY_PET_PKEY = Internal.createUniqueKey(FactoryPet.FACTORY_PET, DSL.name("factory_pet_pkey"), new TableField[] { FactoryPet.FACTORY_PET.ID }, true);
    public static final UniqueKey<PetRecord> PET_PKEY = Internal.createUniqueKey(Pet.PET, DSL.name("pet_pkey"), new TableField[] { Pet.PET.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<FactoryRecord, AppUserRecord> FACTORY__FK_FACTORY_USER = Internal.createForeignKey(Factory.FACTORY, DSL.name("fk_factory_user"), new TableField[] { Factory.FACTORY.USER_ID }, Keys.APP_USER_PKEY, new TableField[] { AppUser.APP_USER.ID }, true);
    public static final ForeignKey<FactoryPetRecord, FactoryRecord> FACTORY_PET__FK_FACTORY_PET_FACTORY = Internal.createForeignKey(FactoryPet.FACTORY_PET, DSL.name("fk_factory_pet_factory"), new TableField[] { FactoryPet.FACTORY_PET.FACTORY_ID }, Keys.FACTORY_PKEY, new TableField[] { Factory.FACTORY.ID }, true);
    public static final ForeignKey<FactoryPetRecord, PetRecord> FACTORY_PET__FK_FACTORY_PET_PET = Internal.createForeignKey(FactoryPet.FACTORY_PET, DSL.name("fk_factory_pet_pet"), new TableField[] { FactoryPet.FACTORY_PET.PET_ID }, Keys.PET_PKEY, new TableField[] { Pet.PET.ID }, true);
}
