/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage;


import fr.versefactory.template.storage.tables.AppUser;
import fr.versefactory.template.storage.tables.Box;
import fr.versefactory.template.storage.tables.BoxPet;
import fr.versefactory.template.storage.tables.Example;
import fr.versefactory.template.storage.tables.Factory;
import fr.versefactory.template.storage.tables.FactoryPet;
import fr.versefactory.template.storage.tables.FlywaySchemaHistory;
import fr.versefactory.template.storage.tables.Pet;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in versefactory.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>versefactory.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>versefactory.box</code>.
     */
    public static final Box BOX = Box.BOX;

    /**
     * The table <code>versefactory.box_pet</code>.
     */
    public static final BoxPet BOX_PET = BoxPet.BOX_PET;

    /**
     * The table <code>versefactory.example</code>.
     */
    public static final Example EXAMPLE = Example.EXAMPLE;

    /**
     * The table <code>versefactory.factory</code>.
     */
    public static final Factory FACTORY = Factory.FACTORY;

    /**
     * The table <code>versefactory.factory_pet</code>.
     */
    public static final FactoryPet FACTORY_PET = FactoryPet.FACTORY_PET;

    /**
     * The table <code>versefactory.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>versefactory.pet</code>.
     */
    public static final Pet PET = Pet.PET;
}
