/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage;


import fr.versefactory.template.storage.tables.AppUser;
import fr.versefactory.template.storage.tables.Box;
import fr.versefactory.template.storage.tables.BoxPet;
import fr.versefactory.template.storage.tables.Example;
import fr.versefactory.template.storage.tables.Factory;
import fr.versefactory.template.storage.tables.FactoryPet;
import fr.versefactory.template.storage.tables.FlywaySchemaHistory;
import fr.versefactory.template.storage.tables.Pet;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Versefactory extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>versefactory</code>
     */
    public static final Versefactory VERSEFACTORY = new Versefactory();

    /**
     * The table <code>versefactory.app_user</code>.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>versefactory.box</code>.
     */
    public final Box BOX = Box.BOX;

    /**
     * The table <code>versefactory.box_pet</code>.
     */
    public final BoxPet BOX_PET = BoxPet.BOX_PET;

    /**
     * The table <code>versefactory.example</code>.
     */
    public final Example EXAMPLE = Example.EXAMPLE;

    /**
     * The table <code>versefactory.factory</code>.
     */
    public final Factory FACTORY = Factory.FACTORY;

    /**
     * The table <code>versefactory.factory_pet</code>.
     */
    public final FactoryPet FACTORY_PET = FactoryPet.FACTORY_PET;

    /**
     * The table <code>versefactory.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>versefactory.pet</code>.
     */
    public final Pet PET = Pet.PET;

    /**
     * No further instances allowed
     */
    private Versefactory() {
        super("versefactory", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AppUser.APP_USER,
            Box.BOX,
            BoxPet.BOX_PET,
            Example.EXAMPLE,
            Factory.FACTORY,
            FactoryPet.FACTORY_PET,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Pet.PET
        );
    }
}
