/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables;


import fr.versefactory.template.storage.Keys;
import fr.versefactory.template.storage.Versefactory;
import fr.versefactory.template.storage.tables.BoxPet.BoxPetPath;
import fr.versefactory.template.storage.tables.Pet.PetPath;
import fr.versefactory.template.storage.tables.records.BoxRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Box extends TableImpl<BoxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>versefactory.box</code>
     */
    public static final Box BOX = new Box();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BoxRecord> getRecordType() {
        return BoxRecord.class;
    }

    /**
     * The column <code>versefactory.box.id</code>.
     */
    public final TableField<BoxRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>versefactory.box.name</code>.
     */
    public final TableField<BoxRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>versefactory.box.description</code>.
     */
    public final TableField<BoxRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>versefactory.box.price</code>.
     */
    public final TableField<BoxRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.NUMERIC.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>versefactory.box.created_at</code>.
     */
    public final TableField<BoxRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Box(Name alias, Table<BoxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Box(Name alias, Table<BoxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>versefactory.box</code> table reference
     */
    public Box(String alias) {
        this(DSL.name(alias), BOX);
    }

    /**
     * Create an aliased <code>versefactory.box</code> table reference
     */
    public Box(Name alias) {
        this(alias, BOX);
    }

    /**
     * Create a <code>versefactory.box</code> table reference
     */
    public Box() {
        this(DSL.name("box"), null);
    }

    public <O extends Record> Box(Table<O> path, ForeignKey<O, BoxRecord> childPath, InverseForeignKey<O, BoxRecord> parentPath) {
        super(path, childPath, parentPath, BOX);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.24"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class BoxPath extends Box implements Path<BoxRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BoxPath(Table<O> path, ForeignKey<O, BoxRecord> childPath, InverseForeignKey<O, BoxRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BoxPath(Name alias, Table<BoxRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BoxPath as(String alias) {
            return new BoxPath(DSL.name(alias), this);
        }

        @Override
        public BoxPath as(Name alias) {
            return new BoxPath(alias, this);
        }

        @Override
        public BoxPath as(Table<?> alias) {
            return new BoxPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Versefactory.VERSEFACTORY;
    }

    @Override
    public UniqueKey<BoxRecord> getPrimaryKey() {
        return Keys.BOX_PKEY;
    }

    private transient BoxPetPath _boxPet;

    /**
     * Get the implicit to-many join path to the
     * <code>versefactory.box_pet</code> table
     */
    public BoxPetPath boxPet() {
        if (_boxPet == null)
            _boxPet = new BoxPetPath(this, null, Keys.BOX_PET__FK_BOX_PET_BOX.getInverseKey());

        return _boxPet;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>versefactory.pet</code> table
     */
    public PetPath pet() {
        return boxPet().pet();
    }

    @Override
    public Box as(String alias) {
        return new Box(DSL.name(alias), this);
    }

    @Override
    public Box as(Name alias) {
        return new Box(alias, this);
    }

    @Override
    public Box as(Table<?> alias) {
        return new Box(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Box rename(String name) {
        return new Box(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Box rename(Name name) {
        return new Box(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Box rename(Table<?> name) {
        return new Box(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Box where(Condition condition) {
        return new Box(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Box where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Box where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Box where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Box where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Box where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Box where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Box where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Box whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Box whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
