/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables;


import fr.versefactory.template.storage.Indexes;
import fr.versefactory.template.storage.Keys;
import fr.versefactory.template.storage.Versefactory;
import fr.versefactory.template.storage.tables.Box.BoxPath;
import fr.versefactory.template.storage.tables.Pet.PetPath;
import fr.versefactory.template.storage.tables.records.BoxPetRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BoxPet extends TableImpl<BoxPetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>versefactory.box_pet</code>
     */
    public static final BoxPet BOX_PET = new BoxPet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BoxPetRecord> getRecordType() {
        return BoxPetRecord.class;
    }

    /**
     * The column <code>versefactory.box_pet.id</code>.
     */
    public final TableField<BoxPetRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>versefactory.box_pet.box_id</code>.
     */
    public final TableField<BoxPetRecord, UUID> BOX_ID = createField(DSL.name("box_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>versefactory.box_pet.pet_id</code>.
     */
    public final TableField<BoxPetRecord, UUID> PET_ID = createField(DSL.name("pet_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>versefactory.box_pet.drop_chance</code>.
     */
    public final TableField<BoxPetRecord, BigDecimal> DROP_CHANCE = createField(DSL.name("drop_chance"), SQLDataType.NUMERIC(5, 2).nullable(false), this, "");

    private BoxPet(Name alias, Table<BoxPetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BoxPet(Name alias, Table<BoxPetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>versefactory.box_pet</code> table reference
     */
    public BoxPet(String alias) {
        this(DSL.name(alias), BOX_PET);
    }

    /**
     * Create an aliased <code>versefactory.box_pet</code> table reference
     */
    public BoxPet(Name alias) {
        this(alias, BOX_PET);
    }

    /**
     * Create a <code>versefactory.box_pet</code> table reference
     */
    public BoxPet() {
        this(DSL.name("box_pet"), null);
    }

    public <O extends Record> BoxPet(Table<O> path, ForeignKey<O, BoxPetRecord> childPath, InverseForeignKey<O, BoxPetRecord> parentPath) {
        super(path, childPath, parentPath, BOX_PET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.24"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class BoxPetPath extends BoxPet implements Path<BoxPetRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BoxPetPath(Table<O> path, ForeignKey<O, BoxPetRecord> childPath, InverseForeignKey<O, BoxPetRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BoxPetPath(Name alias, Table<BoxPetRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BoxPetPath as(String alias) {
            return new BoxPetPath(DSL.name(alias), this);
        }

        @Override
        public BoxPetPath as(Name alias) {
            return new BoxPetPath(alias, this);
        }

        @Override
        public BoxPetPath as(Table<?> alias) {
            return new BoxPetPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Versefactory.VERSEFACTORY;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_BOX_PET_BOX_ID, Indexes.IDX_BOX_PET_PET_ID);
    }

    @Override
    public UniqueKey<BoxPetRecord> getPrimaryKey() {
        return Keys.BOX_PET_PKEY;
    }

    @Override
    public List<UniqueKey<BoxPetRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_BOX_PET);
    }

    @Override
    public List<ForeignKey<BoxPetRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BOX_PET__FK_BOX_PET_BOX, Keys.BOX_PET__FK_BOX_PET_PET);
    }

    private transient BoxPath _box;

    /**
     * Get the implicit join path to the <code>versefactory.box</code> table.
     */
    public BoxPath box() {
        if (_box == null)
            _box = new BoxPath(this, Keys.BOX_PET__FK_BOX_PET_BOX, null);

        return _box;
    }

    private transient PetPath _pet;

    /**
     * Get the implicit join path to the <code>versefactory.pet</code> table.
     */
    public PetPath pet() {
        if (_pet == null)
            _pet = new PetPath(this, Keys.BOX_PET__FK_BOX_PET_PET, null);

        return _pet;
    }

    @Override
    public BoxPet as(String alias) {
        return new BoxPet(DSL.name(alias), this);
    }

    @Override
    public BoxPet as(Name alias) {
        return new BoxPet(alias, this);
    }

    @Override
    public BoxPet as(Table<?> alias) {
        return new BoxPet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BoxPet rename(String name) {
        return new BoxPet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BoxPet rename(Name name) {
        return new BoxPet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BoxPet rename(Table<?> name) {
        return new BoxPet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BoxPet where(Condition condition) {
        return new BoxPet(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BoxPet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BoxPet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BoxPet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BoxPet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BoxPet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BoxPet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BoxPet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BoxPet whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BoxPet whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
