/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables;


import fr.versefactory.template.storage.Indexes;
import fr.versefactory.template.storage.Keys;
import fr.versefactory.template.storage.Versefactory;
import fr.versefactory.template.storage.tables.AppUser.AppUserPath;
import fr.versefactory.template.storage.tables.FactoryPet.FactoryPetPath;
import fr.versefactory.template.storage.tables.FactoryUpgrade.FactoryUpgradePath;
import fr.versefactory.template.storage.tables.Upgrade.UpgradePath;
import fr.versefactory.template.storage.tables.records.FactoryRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Factory extends TableImpl<FactoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>versefactory.factory</code>
     */
    public static final Factory FACTORY = new Factory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FactoryRecord> getRecordType() {
        return FactoryRecord.class;
    }

    /**
     * The column <code>versefactory.factory.id</code>.
     */
    public final TableField<FactoryRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>versefactory.factory.user_id</code>.
     */
    public final TableField<FactoryRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>versefactory.factory.balance</code>.
     */
    public final TableField<FactoryRecord, BigDecimal> BALANCE = createField(DSL.name("balance"), SQLDataType.NUMERIC.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>versefactory.factory.last_updated_at</code>.
     */
    public final TableField<FactoryRecord, LocalDateTime> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>versefactory.factory.max_size</code>.
     */
    public final TableField<FactoryRecord, Integer> MAX_SIZE = createField(DSL.name("max_size"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("6"), SQLDataType.INTEGER)), this, "");

    private Factory(Name alias, Table<FactoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Factory(Name alias, Table<FactoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>versefactory.factory</code> table reference
     */
    public Factory(String alias) {
        this(DSL.name(alias), FACTORY);
    }

    /**
     * Create an aliased <code>versefactory.factory</code> table reference
     */
    public Factory(Name alias) {
        this(alias, FACTORY);
    }

    /**
     * Create a <code>versefactory.factory</code> table reference
     */
    public Factory() {
        this(DSL.name("factory"), null);
    }

    public <O extends Record> Factory(Table<O> path, ForeignKey<O, FactoryRecord> childPath, InverseForeignKey<O, FactoryRecord> parentPath) {
        super(path, childPath, parentPath, FACTORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.24"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class FactoryPath extends Factory implements Path<FactoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FactoryPath(Table<O> path, ForeignKey<O, FactoryRecord> childPath, InverseForeignKey<O, FactoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FactoryPath(Name alias, Table<FactoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FactoryPath as(String alias) {
            return new FactoryPath(DSL.name(alias), this);
        }

        @Override
        public FactoryPath as(Name alias) {
            return new FactoryPath(alias, this);
        }

        @Override
        public FactoryPath as(Table<?> alias) {
            return new FactoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Versefactory.VERSEFACTORY;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_FACTORY_USER_ID);
    }

    @Override
    public UniqueKey<FactoryRecord> getPrimaryKey() {
        return Keys.FACTORY_PKEY;
    }

    @Override
    public List<UniqueKey<FactoryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FACTORY_USER_ID_KEY);
    }

    @Override
    public List<ForeignKey<FactoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FACTORY__FK_FACTORY_USER);
    }

    private transient AppUserPath _appUser;

    /**
     * Get the implicit join path to the <code>versefactory.app_user</code>
     * table.
     */
    public AppUserPath appUser() {
        if (_appUser == null)
            _appUser = new AppUserPath(this, Keys.FACTORY__FK_FACTORY_USER, null);

        return _appUser;
    }

    private transient FactoryUpgradePath _factoryUpgrade;

    /**
     * Get the implicit to-many join path to the
     * <code>versefactory.factory_upgrade</code> table
     */
    public FactoryUpgradePath factoryUpgrade() {
        if (_factoryUpgrade == null)
            _factoryUpgrade = new FactoryUpgradePath(this, null, Keys.FACTORY_UPGRADE__FACTORY_UPGRADE_FACTORY_FK.getInverseKey());

        return _factoryUpgrade;
    }

    private transient FactoryPetPath _factoryPet;

    /**
     * Get the implicit to-many join path to the
     * <code>versefactory.factory_pet</code> table
     */
    public FactoryPetPath factoryPet() {
        if (_factoryPet == null)
            _factoryPet = new FactoryPetPath(this, null, Keys.FACTORY_PET__FK_FACTORY_PET_FACTORY.getInverseKey());

        return _factoryPet;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>versefactory.upgrade</code> table
     */
    public UpgradePath upgrade() {
        return factoryUpgrade().upgrade();
    }

    @Override
    public Factory as(String alias) {
        return new Factory(DSL.name(alias), this);
    }

    @Override
    public Factory as(Name alias) {
        return new Factory(alias, this);
    }

    @Override
    public Factory as(Table<?> alias) {
        return new Factory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Factory rename(String name) {
        return new Factory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Factory rename(Name name) {
        return new Factory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Factory rename(Table<?> name) {
        return new Factory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Factory where(Condition condition) {
        return new Factory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Factory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Factory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Factory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Factory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Factory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Factory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Factory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Factory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Factory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
