/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables;


import fr.versefactory.template.storage.Indexes;
import fr.versefactory.template.storage.Keys;
import fr.versefactory.template.storage.Versefactory;
import fr.versefactory.template.storage.tables.Factory.FactoryPath;
import fr.versefactory.template.storage.tables.Upgrade.UpgradePath;
import fr.versefactory.template.storage.tables.records.FactoryUpgradeRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactoryUpgrade extends TableImpl<FactoryUpgradeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>versefactory.factory_upgrade</code>
     */
    public static final FactoryUpgrade FACTORY_UPGRADE = new FactoryUpgrade();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FactoryUpgradeRecord> getRecordType() {
        return FactoryUpgradeRecord.class;
    }

    /**
     * The column <code>versefactory.factory_upgrade.factory_id</code>.
     */
    public final TableField<FactoryUpgradeRecord, UUID> FACTORY_ID = createField(DSL.name("factory_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>versefactory.factory_upgrade.upgrade_id</code>.
     */
    public final TableField<FactoryUpgradeRecord, String> UPGRADE_ID = createField(DSL.name("upgrade_id"), SQLDataType.VARCHAR(25).nullable(false), this, "");

    /**
     * The column <code>versefactory.factory_upgrade.level</code>.
     */
    public final TableField<FactoryUpgradeRecord, Integer> LEVEL = createField(DSL.name("level"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>versefactory.factory_upgrade.created_at</code>.
     */
    public final TableField<FactoryUpgradeRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>versefactory.factory_upgrade.updated_at</code>.
     */
    public final TableField<FactoryUpgradeRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FactoryUpgrade(Name alias, Table<FactoryUpgradeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FactoryUpgrade(Name alias, Table<FactoryUpgradeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>versefactory.factory_upgrade</code> table
     * reference
     */
    public FactoryUpgrade(String alias) {
        this(DSL.name(alias), FACTORY_UPGRADE);
    }

    /**
     * Create an aliased <code>versefactory.factory_upgrade</code> table
     * reference
     */
    public FactoryUpgrade(Name alias) {
        this(alias, FACTORY_UPGRADE);
    }

    /**
     * Create a <code>versefactory.factory_upgrade</code> table reference
     */
    public FactoryUpgrade() {
        this(DSL.name("factory_upgrade"), null);
    }

    public <O extends Record> FactoryUpgrade(Table<O> path, ForeignKey<O, FactoryUpgradeRecord> childPath, InverseForeignKey<O, FactoryUpgradeRecord> parentPath) {
        super(path, childPath, parentPath, FACTORY_UPGRADE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.24"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class FactoryUpgradePath extends FactoryUpgrade implements Path<FactoryUpgradeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FactoryUpgradePath(Table<O> path, ForeignKey<O, FactoryUpgradeRecord> childPath, InverseForeignKey<O, FactoryUpgradeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FactoryUpgradePath(Name alias, Table<FactoryUpgradeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FactoryUpgradePath as(String alias) {
            return new FactoryUpgradePath(DSL.name(alias), this);
        }

        @Override
        public FactoryUpgradePath as(Name alias) {
            return new FactoryUpgradePath(alias, this);
        }

        @Override
        public FactoryUpgradePath as(Table<?> alias) {
            return new FactoryUpgradePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Versefactory.VERSEFACTORY;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_FACTORY_UPGRADE_FACTORY_ID, Indexes.IDX_FACTORY_UPGRADE_UPGRADE_ID);
    }

    @Override
    public UniqueKey<FactoryUpgradeRecord> getPrimaryKey() {
        return Keys.FACTORY_UPGRADE_PK;
    }

    @Override
    public List<ForeignKey<FactoryUpgradeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FACTORY_UPGRADE__FACTORY_UPGRADE_FACTORY_FK, Keys.FACTORY_UPGRADE__FACTORY_UPGRADE_UPGRADE_FK);
    }

    private transient FactoryPath _factory;

    /**
     * Get the implicit join path to the <code>versefactory.factory</code>
     * table.
     */
    public FactoryPath factory() {
        if (_factory == null)
            _factory = new FactoryPath(this, Keys.FACTORY_UPGRADE__FACTORY_UPGRADE_FACTORY_FK, null);

        return _factory;
    }

    private transient UpgradePath _upgrade;

    /**
     * Get the implicit join path to the <code>versefactory.upgrade</code>
     * table.
     */
    public UpgradePath upgrade() {
        if (_upgrade == null)
            _upgrade = new UpgradePath(this, Keys.FACTORY_UPGRADE__FACTORY_UPGRADE_UPGRADE_FK, null);

        return _upgrade;
    }

    @Override
    public FactoryUpgrade as(String alias) {
        return new FactoryUpgrade(DSL.name(alias), this);
    }

    @Override
    public FactoryUpgrade as(Name alias) {
        return new FactoryUpgrade(alias, this);
    }

    @Override
    public FactoryUpgrade as(Table<?> alias) {
        return new FactoryUpgrade(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FactoryUpgrade rename(String name) {
        return new FactoryUpgrade(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FactoryUpgrade rename(Name name) {
        return new FactoryUpgrade(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FactoryUpgrade rename(Table<?> name) {
        return new FactoryUpgrade(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryUpgrade where(Condition condition) {
        return new FactoryUpgrade(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryUpgrade where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryUpgrade where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryUpgrade where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactoryUpgrade where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactoryUpgrade where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactoryUpgrade where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactoryUpgrade where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryUpgrade whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryUpgrade whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
