/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables;


import fr.versefactory.template.storage.Indexes;
import fr.versefactory.template.storage.Keys;
import fr.versefactory.template.storage.Versefactory;
import fr.versefactory.template.storage.tables.Factory.FactoryPath;
import fr.versefactory.template.storage.tables.Pet.PetPath;
import fr.versefactory.template.storage.tables.records.FactoryPetRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactoryPet extends TableImpl<FactoryPetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>versefactory.factory_pet</code>
     */
    public static final FactoryPet FACTORY_PET = new FactoryPet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FactoryPetRecord> getRecordType() {
        return FactoryPetRecord.class;
    }

    /**
     * The column <code>versefactory.factory_pet.id</code>.
     */
    public final TableField<FactoryPetRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>versefactory.factory_pet.factory_id</code>.
     */
    public final TableField<FactoryPetRecord, UUID> FACTORY_ID = createField(DSL.name("factory_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>versefactory.factory_pet.pet_id</code>.
     */
    public final TableField<FactoryPetRecord, UUID> PET_ID = createField(DSL.name("pet_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>versefactory.factory_pet.acquired_at</code>.
     */
    public final TableField<FactoryPetRecord, LocalDateTime> ACQUIRED_AT = createField(DSL.name("acquired_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private FactoryPet(Name alias, Table<FactoryPetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FactoryPet(Name alias, Table<FactoryPetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>versefactory.factory_pet</code> table reference
     */
    public FactoryPet(String alias) {
        this(DSL.name(alias), FACTORY_PET);
    }

    /**
     * Create an aliased <code>versefactory.factory_pet</code> table reference
     */
    public FactoryPet(Name alias) {
        this(alias, FACTORY_PET);
    }

    /**
     * Create a <code>versefactory.factory_pet</code> table reference
     */
    public FactoryPet() {
        this(DSL.name("factory_pet"), null);
    }

    public <O extends Record> FactoryPet(Table<O> path, ForeignKey<O, FactoryPetRecord> childPath, InverseForeignKey<O, FactoryPetRecord> parentPath) {
        super(path, childPath, parentPath, FACTORY_PET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.24"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class FactoryPetPath extends FactoryPet implements Path<FactoryPetRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FactoryPetPath(Table<O> path, ForeignKey<O, FactoryPetRecord> childPath, InverseForeignKey<O, FactoryPetRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FactoryPetPath(Name alias, Table<FactoryPetRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FactoryPetPath as(String alias) {
            return new FactoryPetPath(DSL.name(alias), this);
        }

        @Override
        public FactoryPetPath as(Name alias) {
            return new FactoryPetPath(alias, this);
        }

        @Override
        public FactoryPetPath as(Table<?> alias) {
            return new FactoryPetPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Versefactory.VERSEFACTORY;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_FACTORY_PET_FACTORY_ID, Indexes.IDX_FACTORY_PET_PET_ID);
    }

    @Override
    public UniqueKey<FactoryPetRecord> getPrimaryKey() {
        return Keys.FACTORY_PET_PKEY;
    }

    @Override
    public List<ForeignKey<FactoryPetRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FACTORY_PET__FK_FACTORY_PET_FACTORY, Keys.FACTORY_PET__FK_FACTORY_PET_PET);
    }

    private transient FactoryPath _factory;

    /**
     * Get the implicit join path to the <code>versefactory.factory</code>
     * table.
     */
    public FactoryPath factory() {
        if (_factory == null)
            _factory = new FactoryPath(this, Keys.FACTORY_PET__FK_FACTORY_PET_FACTORY, null);

        return _factory;
    }

    private transient PetPath _pet;

    /**
     * Get the implicit join path to the <code>versefactory.pet</code> table.
     */
    public PetPath pet() {
        if (_pet == null)
            _pet = new PetPath(this, Keys.FACTORY_PET__FK_FACTORY_PET_PET, null);

        return _pet;
    }

    @Override
    public FactoryPet as(String alias) {
        return new FactoryPet(DSL.name(alias), this);
    }

    @Override
    public FactoryPet as(Name alias) {
        return new FactoryPet(alias, this);
    }

    @Override
    public FactoryPet as(Table<?> alias) {
        return new FactoryPet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FactoryPet rename(String name) {
        return new FactoryPet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FactoryPet rename(Name name) {
        return new FactoryPet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FactoryPet rename(Table<?> name) {
        return new FactoryPet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryPet where(Condition condition) {
        return new FactoryPet(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryPet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryPet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryPet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactoryPet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactoryPet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactoryPet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactoryPet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryPet whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactoryPet whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
