/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables;


import fr.versefactory.template.storage.Keys;
import fr.versefactory.template.storage.Versefactory;
import fr.versefactory.template.storage.tables.Box.BoxPath;
import fr.versefactory.template.storage.tables.BoxPet.BoxPetPath;
import fr.versefactory.template.storage.tables.FactoryPet.FactoryPetPath;
import fr.versefactory.template.storage.tables.records.PetRecord;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Pet extends TableImpl<PetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>versefactory.pet</code>
     */
    public static final Pet PET = new Pet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PetRecord> getRecordType() {
        return PetRecord.class;
    }

    /**
     * The column <code>versefactory.pet.id</code>.
     */
    public final TableField<PetRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>versefactory.pet.name</code>.
     */
    public final TableField<PetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>versefactory.pet.rarity</code>.
     */
    public final TableField<PetRecord, String> RARITY = createField(DSL.name("rarity"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>versefactory.pet.income_per_second</code>.
     */
    public final TableField<PetRecord, BigDecimal> INCOME_PER_SECOND = createField(DSL.name("income_per_second"), SQLDataType.NUMERIC.defaultValue(DSL.field(DSL.raw("1.0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>versefactory.pet.base_cost</code>.
     */
    public final TableField<PetRecord, BigDecimal> BASE_COST = createField(DSL.name("base_cost"), SQLDataType.NUMERIC.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    private Pet(Name alias, Table<PetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Pet(Name alias, Table<PetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>versefactory.pet</code> table reference
     */
    public Pet(String alias) {
        this(DSL.name(alias), PET);
    }

    /**
     * Create an aliased <code>versefactory.pet</code> table reference
     */
    public Pet(Name alias) {
        this(alias, PET);
    }

    /**
     * Create a <code>versefactory.pet</code> table reference
     */
    public Pet() {
        this(DSL.name("pet"), null);
    }

    public <O extends Record> Pet(Table<O> path, ForeignKey<O, PetRecord> childPath, InverseForeignKey<O, PetRecord> parentPath) {
        super(path, childPath, parentPath, PET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.24"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class PetPath extends Pet implements Path<PetRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PetPath(Table<O> path, ForeignKey<O, PetRecord> childPath, InverseForeignKey<O, PetRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PetPath(Name alias, Table<PetRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PetPath as(String alias) {
            return new PetPath(DSL.name(alias), this);
        }

        @Override
        public PetPath as(Name alias) {
            return new PetPath(alias, this);
        }

        @Override
        public PetPath as(Table<?> alias) {
            return new PetPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Versefactory.VERSEFACTORY;
    }

    @Override
    public UniqueKey<PetRecord> getPrimaryKey() {
        return Keys.PET_PKEY;
    }

    private transient BoxPetPath _boxPet;

    /**
     * Get the implicit to-many join path to the
     * <code>versefactory.box_pet</code> table
     */
    public BoxPetPath boxPet() {
        if (_boxPet == null)
            _boxPet = new BoxPetPath(this, null, Keys.BOX_PET__FK_BOX_PET_PET.getInverseKey());

        return _boxPet;
    }

    private transient FactoryPetPath _factoryPet;

    /**
     * Get the implicit to-many join path to the
     * <code>versefactory.factory_pet</code> table
     */
    public FactoryPetPath factoryPet() {
        if (_factoryPet == null)
            _factoryPet = new FactoryPetPath(this, null, Keys.FACTORY_PET__FK_FACTORY_PET_PET.getInverseKey());

        return _factoryPet;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>versefactory.box</code> table
     */
    public BoxPath box() {
        return boxPet().box();
    }

    @Override
    public Pet as(String alias) {
        return new Pet(DSL.name(alias), this);
    }

    @Override
    public Pet as(Name alias) {
        return new Pet(alias, this);
    }

    @Override
    public Pet as(Table<?> alias) {
        return new Pet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pet rename(String name) {
        return new Pet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pet rename(Name name) {
        return new Pet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pet rename(Table<?> name) {
        return new Pet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet where(Condition condition) {
        return new Pet(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Pet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Pet whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
