/*
 * This file is generated by jOOQ.
 */
package fr.versefactory.template.storage.tables;


import fr.versefactory.template.storage.Keys;
import fr.versefactory.template.storage.Versefactory;
import fr.versefactory.template.storage.tables.Factory.FactoryPath;
import fr.versefactory.template.storage.tables.FactoryUpgrade.FactoryUpgradePath;
import fr.versefactory.template.storage.tables.records.UpgradeRecord;

import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.24"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Upgrade extends TableImpl<UpgradeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>versefactory.upgrade</code>
     */
    public static final Upgrade UPGRADE = new Upgrade();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UpgradeRecord> getRecordType() {
        return UpgradeRecord.class;
    }

    /**
     * The column <code>versefactory.upgrade.id</code>.
     */
    public final TableField<UpgradeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(25).nullable(false), this, "");

    /**
     * The column <code>versefactory.upgrade.name</code>.
     */
    public final TableField<UpgradeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>versefactory.upgrade.description</code>.
     */
    public final TableField<UpgradeRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>versefactory.upgrade.type</code>.
     */
    public final TableField<UpgradeRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>versefactory.upgrade.max_level</code>.
     */
    public final TableField<UpgradeRecord, Integer> MAX_LEVEL = createField(DSL.name("max_level"), SQLDataType.INTEGER, this, "");

    private Upgrade(Name alias, Table<UpgradeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Upgrade(Name alias, Table<UpgradeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>versefactory.upgrade</code> table reference
     */
    public Upgrade(String alias) {
        this(DSL.name(alias), UPGRADE);
    }

    /**
     * Create an aliased <code>versefactory.upgrade</code> table reference
     */
    public Upgrade(Name alias) {
        this(alias, UPGRADE);
    }

    /**
     * Create a <code>versefactory.upgrade</code> table reference
     */
    public Upgrade() {
        this(DSL.name("upgrade"), null);
    }

    public <O extends Record> Upgrade(Table<O> path, ForeignKey<O, UpgradeRecord> childPath, InverseForeignKey<O, UpgradeRecord> parentPath) {
        super(path, childPath, parentPath, UPGRADE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.24"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class UpgradePath extends Upgrade implements Path<UpgradeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UpgradePath(Table<O> path, ForeignKey<O, UpgradeRecord> childPath, InverseForeignKey<O, UpgradeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UpgradePath(Name alias, Table<UpgradeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UpgradePath as(String alias) {
            return new UpgradePath(DSL.name(alias), this);
        }

        @Override
        public UpgradePath as(Name alias) {
            return new UpgradePath(alias, this);
        }

        @Override
        public UpgradePath as(Table<?> alias) {
            return new UpgradePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Versefactory.VERSEFACTORY;
    }

    @Override
    public UniqueKey<UpgradeRecord> getPrimaryKey() {
        return Keys.UPGRADE_PKEY;
    }

    private transient FactoryUpgradePath _factoryUpgrade;

    /**
     * Get the implicit to-many join path to the
     * <code>versefactory.factory_upgrade</code> table
     */
    public FactoryUpgradePath factoryUpgrade() {
        if (_factoryUpgrade == null)
            _factoryUpgrade = new FactoryUpgradePath(this, null, Keys.FACTORY_UPGRADE__FACTORY_UPGRADE_UPGRADE_FK.getInverseKey());

        return _factoryUpgrade;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>versefactory.factory</code> table
     */
    public FactoryPath factory() {
        return factoryUpgrade().factory();
    }

    @Override
    public Upgrade as(String alias) {
        return new Upgrade(DSL.name(alias), this);
    }

    @Override
    public Upgrade as(Name alias) {
        return new Upgrade(alias, this);
    }

    @Override
    public Upgrade as(Table<?> alias) {
        return new Upgrade(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Upgrade rename(String name) {
        return new Upgrade(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Upgrade rename(Name name) {
        return new Upgrade(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Upgrade rename(Table<?> name) {
        return new Upgrade(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Upgrade where(Condition condition) {
        return new Upgrade(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Upgrade where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Upgrade where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Upgrade where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Upgrade where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Upgrade where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Upgrade where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Upgrade where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Upgrade whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Upgrade whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
