name: Deploy Image to env

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'sandbox'
        type: choice
        options:
          - sandbox
          - dev
          - qual
          - rec
      tag:
        description: 'Select tag'
        required: true
        default: 'main'
        type: string
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      tag:
        description: 'Tag to deploy'
        required: true
        type: string
run-name: "Déploiement vers ${{ inputs.environment }} - Tag ${{ inputs.tag }}"
jobs:
  call-deploy-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call Deploy Action
        uses: e-mothep/shared-workflow-docker/.github/common/deploy@main
        with:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PEM : ${{ secrets.APP_PEM }}
          path: kustomize
          env: ${{ github.event.inputs.environment }}
          app: ${{ github.event.repository.name }}
          version: ${{ github.event.inputs.tag }}
          repository: e-mothep/kustomize-YOUR-APP-HERE
