name: Quality check

on:
  workflow_dispatch:

jobs:
  quality-check:
    runs-on: [ self-hosted, linux, back ]
    steps:
      - name: Quality Check with SonarQube
        uses: e-mothep/shared-workflow-docker/.github/java/quality@main
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_PROPERTIES: ${{ secrets.SONAR_PROJECT_PROPERTIES }}
          SONAR_PROJECT_NAME: ${{ github.event.repository.name }}
          SKIP_TEST: false