spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: versefactory

server:
  port: ${PORT:8080}
