<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.3</version>
		<relativePath/>
	</parent>
	<groupId>fr.versefactory.template</groupId>
	<artifactId>template-spring-app-back</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<name>template-spring-app-back</name>
	<description>Template pour les futurs projets Spring Boot</description>
	<properties>
		<java.version>21</java.version>

		<openapi-common-generator.base-package>fr.versefactory.template.v1.common.openapi</openapi-common-generator.base-package>
		<openapi-common-generator.input-spec>${project.basedir}\src\main\resources\openapi\openapi-common-v1.yaml</openapi-common-generator.input-spec>
		<openapi-common-package-name>v1.common.openapi</openapi-common-package-name>

		<openapi-admin-generator.base-package>fr.versefactory.template.v1.admin.openapi</openapi-admin-generator.base-package>
		<openapi-admin-generator.input-spec>${project.basedir}\src\main\resources\openapi\openapi-admin-v1.yaml</openapi-admin-generator.input-spec>
		<openapi-admin-package-name>v1.admin.openapi</openapi-admin-package-name>

		<org.flywaydb.version>11.2.0</org.flywaydb.version>
		<org.projectlombok.version>1.18.36</org.projectlombok.version>
		<org.postgresql.version>42.7.5</org.postgresql.version>
		<springdoc.version>2.8.4</springdoc.version>
		<org.mapstruct.version>1.6.3</org.mapstruct.version>
		<lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
		<openapi-generator-maven-plugin.version>7.11.0</openapi-generator-maven-plugin.version>
		<jackson-databind-nullable.version>0.2.6</jackson-databind-nullable.version>
		<sonar.coverage.jacoco.xmlReportPaths>target/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
		<sonar.coverage.jacoco.version>0.8.12</sonar.coverage.jacoco.version>

		<registry>harbor.versefactory.com/template/template-spring-app-back</registry>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-oauth2-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jooq</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-jose</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>

		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-database-postgresql</artifactId>
			<version>${org.flywaydb.version}</version>
		</dependency>
		<dependency>
			<groupId>org.flywaydb.flyway-test-extensions</groupId>
			<artifactId>flyway-spring-test</artifactId>
			<version>10.0.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>${org.postgresql.version}</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${org.projectlombok.version}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>${springdoc.version}</version>
		</dependency>

		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-processor</artifactId>
			<version>${org.mapstruct.version}</version>
		</dependency>

		<dependency>
			<groupId>org.openapitools</groupId>
			<artifactId>jackson-databind-nullable</artifactId>
			<version>${jackson-databind-nullable.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-commons</artifactId>
		</dependency>
		<dependency>
    		<groupId>org.keycloak</groupId>
    		<artifactId>keycloak-admin-client</artifactId>
    		<version>26.0.0</version>
		</dependency>

		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>testcontainers</artifactId>
			<version>1.20.4</version>
			<scope>compile</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>postgresql</artifactId>
			<version>1.20.4</version>
			<scope>test</scope>
		</dependency>

		<!-- Minio -->
		<dependency>
			<groupId>io.minio</groupId>
			<artifactId>minio</artifactId>
			<version>8.6.0</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>${sonar.coverage.jacoco.version}</version>
				<configuration>
					<excludes>
						<exclude>**/jooq/**/*</exclude>
						<exclude>**/openapi-common/**/*</exclude>
					</excludes>
				</configuration>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>verify</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							<formats>
								<format>XML</format>
							</formats>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${org.projectlombok.version}</version>
						</path>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok-mapstruct-binding</artifactId>
							<version>${lombok-mapstruct-binding.version}</version>
						</path>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${org.mapstruct.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<image>
						<name>${registry}</name>
						<tags>${registry}:${version}</tags>
						<publish>false</publish>
					</image>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>add-jooq-sources</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>src/main/jooq</source>
							</sources>
						</configuration>
					</execution>
					<execution>
						<id>add-openapi-common-sources</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>src/main/openapi-common-v1</source>
							</sources>
						</configuration>
					</execution>
					<execution>
						<id>add-openapi-admin-sources</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>src/main/openapi-admin-v1</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>generate-jooq</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.jooq</groupId>
						<artifactId>jooq-codegen-maven</artifactId>
						<executions>
							<execution>
								<id>generate-jooq-sources</id>
								<phase>generate-sources</phase>
								<goals>
									<goal>generate</goal>
								</goals>
							</execution>
						</executions>
						<dependencies>
							<dependency>
								<groupId>org.postgresql</groupId>
								<artifactId>postgresql</artifactId>
								<version>${org.postgresql.version}</version>
							</dependency>
						</dependencies>
						<configuration>
							<jdbc>
								<driver>org.postgresql.Driver</driver>
								<url>jdbc:postgresql://localhost:5432/verseFactory_db</url>
								<username>factory</username>
								<password>factory</password>
							</jdbc>
							<generator>
								<database>
									<name>org.jooq.meta.postgres.PostgresDatabase</name>
									<includes>.*</includes>
									<inputSchema>versefactory</inputSchema>
								</database>
								<generate>
									<relations>true</relations>
									<deprecated>false</deprecated>
									<instanceFields>true</instanceFields>
									<generatedAnnotation>true</generatedAnnotation>
									<records>true</records>
									<pojos>false</pojos>
									<daos>false</daos>
									<interfaces>false</interfaces>
									<jpaAnnotations>false</jpaAnnotations>
									<validationAnnotations>true</validationAnnotations>
									<globalObjectReferences>true</globalObjectReferences>
									<fluentSetters>true</fluentSetters>
								</generate>
								<target>
									<packageName>fr.versefactory.template.storage</packageName>
									<directory>src/main/jooq</directory>
								</target>
							</generator>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>generate-openapi-common-v1</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.openapitools</groupId>
						<artifactId>openapi-generator-maven-plugin</artifactId>
						<version>${openapi-generator-maven-plugin.version}</version>
						<executions>
							<execution>
								<id>generate-openapi-common</id>
								<phase>generate-sources</phase>
								<goals>
									<goal>generate</goal>
								</goals>
								<configuration>
									<output>${project.build.directory}/generated-sources/${openapi-common-package-name}</output>
									<generateSupportingFiles>true</generateSupportingFiles>
									<generatorName>spring</generatorName>
									<cleanupOutput>true</cleanupOutput>
									<apiPackage>${openapi-common-generator.base-package}.endpoint</apiPackage>
									<generateApiTests>true</generateApiTests>
									<generateModelTests>true</generateModelTests>
									<groupId>${project.groupId}</groupId>
									<inputSpec>${openapi-common-generator.input-spec}</inputSpec>
									<invokerPackage>${openapi-common-generator.base-package}.invoker</invokerPackage>
									<modelPackage>${openapi-common-generator.base-package}.payload</modelPackage>
									<configOptions>
										<sourceFolder>/</sourceFolder>
										<generatorLanguage>Java</generatorLanguage>
										<generatorType>SERVER</generatorType>
										<basePackage>${openapi-common-generator.base-package}</basePackage>
										<configPackage>${openapi-common-generator.base-package}.configuration</configPackage>
										<delegatePattern>false</delegatePattern>
										<useSingleRequestParameter>true</useSingleRequestParameter>
										<performBeanValidation>true</performBeanValidation>
										<serializableModel>true</serializableModel>
										<title>Template Common API</title>
										<unhandledException>true</unhandledException>
										<useSpringBoot3>true</useSpringBoot3>
										<useSpringController>true</useSpringController>
										<interfaceOnly>true</interfaceOnly>
										<hideGenerationTimestamp>true</hideGenerationTimestamp>
									</configOptions>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>3.1.0</version>
						<executions>
							<execution>
								<id>copy-openapi-common-generated-sources</id>
								<phase>generate-sources</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<target>
										<mkdir dir="${project.basedir}/src/main/openapi-common-v1"/>
										<mkdir dir="${project.basedir}/docs/openapi"/>
										<move todir="${project.basedir}/src/main/openapi-common-v1">
											<fileset dir="${project.build.directory}/generated-sources/${openapi-common-package-name}">
												<include name="fr/**"/>
											</fileset>
										</move>
										<copy file="${openapi-common-generator.input-spec}" todir="${project.basedir}/docs/openapi"/>
									</target>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>generate-openapi-admin-v1</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.openapitools</groupId>
						<artifactId>openapi-generator-maven-plugin</artifactId>
						<version>${openapi-generator-maven-plugin.version}</version>
						<executions>
							<execution>
								<id>generate-openapi-admin</id>
								<phase>generate-sources</phase>
								<goals>
									<goal>generate</goal>
								</goals>
								<configuration>
									<output>${project.build.directory}/generated-sources/${openapi-admin-package-name}</output>
									<generateSupportingFiles>true</generateSupportingFiles>
									<generatorName>spring</generatorName>
									<cleanupOutput>true</cleanupOutput>
									<apiPackage>${openapi-admin-generator.base-package}.endpoint</apiPackage>
									<generateApiTests>true</generateApiTests>
									<generateModelTests>true</generateModelTests>
									<groupId>${project.groupId}</groupId>
									<inputSpec>${openapi-admin-generator.input-spec}</inputSpec>
									<invokerPackage>${openapi-admin-generator.base-package}.invoker</invokerPackage>
									<modelPackage>${openapi-admin-generator.base-package}.payload</modelPackage>
									<configOptions>
										<sourceFolder>/</sourceFolder>
										<generatorLanguage>Java</generatorLanguage>
										<generatorType>SERVER</generatorType>
										<basePackage>${openapi-admin-generator.base-package}</basePackage>
										<configPackage>${openapi-admin-generator.base-package}.configuration</configPackage>
										<delegatePattern>false</delegatePattern>
										<useSingleRequestParameter>true</useSingleRequestParameter>
										<performBeanValidation>true</performBeanValidation>
										<serializableModel>true</serializableModel>
										<title>Template Admin API</title>
										<unhandledException>true</unhandledException>
										<useSpringBoot3>true</useSpringBoot3>
										<useSpringController>true</useSpringController>
										<interfaceOnly>true</interfaceOnly>
										<hideGenerationTimestamp>true</hideGenerationTimestamp>
									</configOptions>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-antrun-plugin</artifactId>
						<version>3.1.0</version>
						<executions>
							<execution>
								<id>copy-openapi-admin-generated-sources</id>
								<phase>generate-sources</phase>
								<goals>
									<goal>run</goal>
								</goals>
								<configuration>
									<target>
										<mkdir dir="${project.basedir}/src/main/openapi-admin-v1"/>
										<mkdir dir="${project.basedir}/docs/openapi"/>
										<move todir="${project.basedir}/src/main/openapi-admin-v1">
											<fileset dir="${project.build.directory}/generated-sources/${openapi-admin-package-name}">
												<include name="fr/**"/>
											</fileset>
										</move>
										<copy file="${openapi-admin-generator.input-spec}" todir="${project.basedir}/docs/openapi"/>
									</target>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
